# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_1',
            field=models.TextField(default=b'none'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_2',
            field=models.TextField(default=b'none'),
        ),
    ]
