# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20190520_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='number',
            field=models.IntegerField(default=b'0'),
        ),
    ]
