# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_step_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='number',
            field=models.IntegerField(),
        ),
    ]
