# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_recipe_total_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='total_steps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='set_timer_amount',
            field=models.IntegerField(),
        ),
    ]
