# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_auto_20190527_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'steps/'),
        ),
        migrations.AlterField(
            model_name='step',
            name='set_timer_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
