# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_auto_20190527_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='photo',
        ),
    ]
